# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossm" do
  name "gossm"
  desc "Tool to connect to aws resources."
  homepage "https://github.com/bovinemagnet/gossm"
  version "0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossm"

  on_macos do
    on_intel do
      url "https://github.com/bovinemagnet/gossm/releases/download/v#{version}/gossm_#{version}_Darwin_x86_64_homebrew.tar.gz"
      sha256 "db0fca7a022335bba9c9c290deb0a2e2d3cd537b68eb5b7fae48590b203cfe5b"
    end
    on_arm do
      url "https://github.com/bovinemagnet/gossm/releases/download/v#{version}/gossm_#{version}_Darwin_arm64_homebrew.tar.gz"
      sha256 "bf9fad0b49ccb1ffdb736c34a7969f28bd3e2856c55cc7d0a32696f5d50bfd13"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bovinemagnet/gossm/releases/download/v#{version}/gossm_#{version}_Linux_x86_64_homebrew.tar.gz"
      sha256 "c9facaa2989334151a6fa58fbb6ac6ef9d65400bb0a05cded1f3de59fd5dd6a0"
    end
    on_arm do
      url "https://github.com/bovinemagnet/gossm/releases/download/v#{version}/gossm_#{version}_Linux_arm64_homebrew.tar.gz"
      sha256 "7f0f57b5daa61fe9a81980c369ebcc97b1bf99e2a41f6cbe39c1c9505d7f0929"
    end
  end

  # No zap stanza required
end
