# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossm" do
  name "gossm"
  desc "Tool to connect to aws resources."
  homepage "https://github.com/bovinemagnet/gossm"
  version "0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossm"

  on_macos do
    on_intel do
      url "https://github.com/bovinemagnet/gossm/releases/download/v#{version}/gossm_#{version}_Darwin_x86_64_homebrew.tar.gz"
      sha256 "84579f091891bfc9662f8b731022c82c091461dc32c5ec2181b70259e4f9f0ae"
    end
    on_arm do
      url "https://github.com/bovinemagnet/gossm/releases/download/v#{version}/gossm_#{version}_Darwin_arm64_homebrew.tar.gz"
      sha256 "c22046c579d68cc6de6d5a7f96a07c7f8f7c26cec408d0b06d89bfed694a9cfa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bovinemagnet/gossm/releases/download/v#{version}/gossm_#{version}_Linux_x86_64_homebrew.tar.gz"
      sha256 "1bed5edd63cb4f76a9957d20d5a2361db770b8a7dc7c670ee7b95bdb6e856c9e"
    end
    on_arm do
      url "https://github.com/bovinemagnet/gossm/releases/download/v#{version}/gossm_#{version}_Linux_arm64_homebrew.tar.gz"
      sha256 "513903551dca205c313c363dda388e6bce34e22a8d661a224a0c1e1bd5542a51"
    end
  end

  # No zap stanza required
end
