# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GraphqlsToAsciidoc < Formula
  desc "Convert GraphQL schema files to comprehensive AsciiDoc documentation"
  homepage "https://github.com/bovinemagnet/graphqls-to-asciidoc"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.2/graphqls-to-asciidoc_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "20230e68ba6f9f5b6d1a1c44b0eacd3948e9315d4afcabc6587ecc6421e1349e"

      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.2/graphqls-to-asciidoc_0.1.2_Darwin_arm64.tar.gz"
      sha256 "ca1ae64219cd312199316025a0570e44175bae3a04948fd265b0a4d0ea8e7d95"

      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.2/graphqls-to-asciidoc_0.1.2_Linux_x86_64.tar.gz"
      sha256 "a5d0c9639cf75701fc12785d9f1c4c2b94850895d75cf67f5d6a53db661b79a2"
      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.2/graphqls-to-asciidoc_0.1.2_Linux_arm64.tar.gz"
      sha256 "280b333ac5f34ad9757534730b0b691ff5673e0e39add912acfd15628a5a9390"
      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
  end

  test do
    system "#{bin}/graphqls-to-asciidoc -version"
  end
end
