# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GraphqlsToAsciidoc < Formula
  desc "Convert GraphQL schema files to comprehensive AsciiDoc documentation"
  homepage "https://github.com/bovinemagnet/graphqls-to-asciidoc"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.4/graphqls-to-asciidoc_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "0f2f2789d2e4ecff5c28357199c14857313191375b2246ca769f95f2a70871f2"

      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.4/graphqls-to-asciidoc_0.1.4_Darwin_arm64.tar.gz"
      sha256 "f56feb6da751cf69b8ce9883bce79e977623903373177cf7eacb1ba889f50898"

      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.4/graphqls-to-asciidoc_0.1.4_Linux_x86_64.tar.gz"
      sha256 "c659dfe7d6c916dfd045c2acc861d967e633bf97eaa50b8345e1943eb402c6d0"
      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.4/graphqls-to-asciidoc_0.1.4_Linux_arm64.tar.gz"
      sha256 "019fd04882bf6ca9b61a4a8d15492077811d89a30c8293d11ba90f059e294ce7"
      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
  end

  test do
    system "#{bin}/graphqls-to-asciidoc -version"
  end
end
