# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GraphqlsToAsciidoc < Formula
  desc "Convert GraphQL schema files to comprehensive AsciiDoc documentation"
  homepage "https://github.com/bovinemagnet/graphqls-to-asciidoc"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.9/graphqls-to-asciidoc_0.1.9_Darwin_x86_64_v1.tar.gz"
      sha256 "758816f391a39f9f5daa5d2ba09d22094a7bd2e6f3376d59d8c075d16d07f0b1"

      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.9/graphqls-to-asciidoc_0.1.9_Darwin_arm64.tar.gz"
      sha256 "4755889fe762c28dacb3ba7492375aa645e887cb88cbb09441cf14f5144cf955"

      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.9/graphqls-to-asciidoc_0.1.9_Linux_x86_64_v1.tar.gz"
      sha256 "23a0bbd7c1255e23314555dd1b37a7e907aa7095c70b2e8616fb9f6d356a4705"
      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/bovinemagnet/graphqls-to-asciidoc/releases/download/0.1.9/graphqls-to-asciidoc_0.1.9_Linux_arm64.tar.gz"
      sha256 "120ce60b872fcb2d1048c0a4acba3cb55e53f17316186ec8b7586ef60e166702"
      def install
        bin.install "graphqls-to-asciidoc"
      end
    end
  end

  test do
    system "#{bin}/graphqls-to-asciidoc -version"
  end
end
